version: '3'
services:
  cypress-test-container:
     image: nate:image:latest
     volumes:
       - type: bind
         source: /path/to/local/storage or ENV Example: ${PWD}
         target: /path/to/container/storage
         read_only: true
