version: '3'
services:
  pa11y-test-container:
     image: <container image>
     volumes:
       - type: bind
         source: /path/to/local/storage or ENV Example: ${PWD}
         target: /pa11y-dashboard/config
         read_only: true
